daemon:
    name: Astron Cluster

general:
    eventlogger: 127.0.0.1:7197
    dc_files:
        - ../toon.dc

messagedirector:
    bind: 127.0.0.1:7199

uberdogs:
    - class: AccountManager
      id: 1001
      anonymous: true

    - class: AvatarManager
      id: 1002
      anonymous: false

roles:
    - type: clientagent
      bind: 0.0.0.0:7198
      version: "sv1.0.0.0"
      client:
       relocate: true
       add_interest: enabled
      channels:
        min: 1000000000
        max: 1009999999

    - type: stateserver
      control: 10000

    - type: database
      control: 4003
      generate:
        min: 100000000
        max: 399999999
      backend:
        type: yaml
        foldername: ../../databases/astrondb

    - type: dbss
      database: 4003
      ranges:
        - min: 100000000
          max: 399999999

    - type: eventlogger
      bind: 127.0.0.1:7197
      output: logs/events-%y%m%d_%H%M%S.log