id: 100000000
class: AccountManager
fields:
  ACCOUNT_USERNAME: "\"ZGV2\""
  ACCOUNT_PASSWORD: "\"MTIzNDU=\""
  ACCOUNT_TIME_CREATED: "\"2016-06-03 18:35:35\""
  ACCOUNT_LAST_LOGIN: "\"2016-06-03 18:35:35\""